# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "SB-486"
product_name = "SB-486"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Subor"
chip = "rp2040"

[matrix]
# RP2040 SuperMini
row_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
col_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11", "PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_26"]

[layout]
rows = 8
cols = 9
layers = 4
matrix_map = """
      (1,1) (1,0) (1,8) (1,6)       (1,3) (1,7) (1,5) (1,2)                               (7,4)
(1,4) (4,4) (0,1) (4,1) (0,0) (4,0) (4,8) (0,6) (4,6) (0,3) (4,3) (0,7) (4,7) (4,5) (2,2) (0,2) (6,2) (3,2)
      (0,4) (3,1) (3,0) (3,8) (0,8) (2,6) (3,6) (2,3) (3,3) (3,7) (3,5) (0,5) (2,5)       (4,2)       (5,2)
(2,4) (3,4) (5,1) (2,1) (5,0) (2,0) (2,8) (6,6) (5,6) (5,3) (2,7) (5,7)
(6,7) (5,4) (6,1) (7,0) (6,0) (6,8) (5,8) (7,6) (7,3) (6,3) (7,7)                               (5,5)
(6,4)       (7,1)             (7,8)                                                       (7,5) (6,5) (7,2)
"""

[[layer]]
name = "base"
keys = """
    F1 F2 F3 F4 F5 F6 F7 F8                            MediaPlayPause
Esc 1 2 3 4 5 6 7 8 9 0 Minus Equal Slash Backspace    Insert Home PageUp
    Q W E R T Y U I O P LeftBracket RightBracket Enter Delete      PageDown
CapsLock A S D F G H J K L Semicolon Quote
LShift Z X C V B N M Comma Dot Slash                          Up
LCtrl  LAlt    Space                                     Left Down Right
"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false
