# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "SB-486"
product_name = "SB-486"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Subor"
chip = "rp2040"

[matrix]
# RP2040 SuperMini
row_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
col_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11", "PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_26"]

[layout]
rows = 8
cols = 9
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8)
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) (5,6) (5,7) (5,8)
(6,0) (6,1) (6,2) (6,3) (6,4) (6,5) (6,6) (6,7) (6,8)
(7,0) (7,1) (7,2) (7,3) (7,4) (7,5) (7,6) (7,7) (7,8)
"""

[[layer]]
name = "base"
keys = """
Kc4 Kc2 Insert Kc9 Q RightBracket Kc7 Minus T
F2 F1 F8 F5 Escape F7 F4 F6 F3
G D Backspace I CapsLock Enter Y Semicolon H
E W PageUp O A LeftBracket U P R
Kc5 Kc3 Delete Kc0 Kc1 Backslash  Kc8 Equal Kc6
F S PageDown L Z Up K Quote N
V X Home Dot LCtrl Down J LShift B
C LAlt Right Comma MediaPlayPause Left M Slash Space
"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false
